issue: FileSystemCache.Set fails on windows with OSError
pallets/cachelib pull request #12
Opened 2020-05-15 22:56 UTC by snjypl

FileSystemCache.Set fails on windows with OSError 

`
line 158, in set
    os.rename(tmp, filename)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 
on windows os.rename raises OSError if the dst file already exist. 
`
it is because of `os.rename`. on windows it throws OSError if the dst exists. 

it is suggested to use `os.replace` if we intend to overwrite the destination file

2020-05-16 07:55 UTC, merged

2020-05-26 21:16 UTC, Adityashaw commented
When will this be released on 'pip'?

Alternatively, how can I use it now?

2020-05-29 18:56 UTC, snjypl commented
@Adityashaw  not sure when it is going to be available on pip. 
in the mean while maybe you could try installing from git. 
`pip install git+https://github.com/pallets/cachelib.git@master`

2020-06-15 18:29 UTC, rayluo commented
Adityashaw commented 20 days ago •

> When will this be released on `pip`?

@lepture ^^^  ?

2020-06-20 08:32 UTC, villebro commented
@davidism @lepture Are there any plans on releasing a new versions on PyPI? Not being able to use on Windows seems like a pretty big problem that merits a `0.1.1` release IMO.

2020-06-20 11:53 UTC, lepture commented
`0.1.1` was released.

2021-04-05 04:26 UTC, nirawat2564 requested changes
<!-- removed -->